name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Requirements
        run: sudo apt-get install doxygen
          && sudo apt-get install python3-sphinx
          && pip install sphinx-rtd-theme
          && pip install breathe
          && pip install sphinx-sitemap
      - name: Checkout repo
        uses: actions/checkout@1.0.0
      - name: Build docs
        run: mkdir build
          && cd build
          && cmake ..
          && make Doxygen
          && make Sphinx
          && touch docs/sphinx/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs_sphinx/_build/html # The folder the action should deploy.
